name = "GalaxyGenerator"
uuid = "40110415-7b45-4700-a6dd-62a19fc43a87"
version = "0.1.0"
authors = ["cgarling <chris.t.garling@gmail.com> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Cosmology = "ed9d9147-8919-4a75-999c-a1043df61e62"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
PhotometricFilters = "482c37c2-cde1-4201-a412-83b81535d120"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[sources]
Cosmology = {url = "https://github.com/cgarling/Cosmology.jl", rev = "main"}

[compat]
ArgCheck = "2"
Compat = "4"
DataInterpolations = "8"
DelimitedFiles = "<0.0.1, 1"
Distributions = "0.25"
Documenter = "1"
FITSIO = "0.17"
HCubature = "1"
IrrationalConstants = "0.2"
PhotometricFilters = "1"
QuadGK = "1, 2"
Random = "<0.0.1, 1"
SpecialFunctions = "2"
StaticArrays = "1"
Statistics = "<0.0.1, 1"
Trapz = "2"
Unitful = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 1"
UnitfulAstro = "1"
julia = "1.10"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[targets]
test = ["Documenter", "QuadGK", "Test", "SafeTestsets", "Unitful", "UnitfulAstro"]
