name = "GalaxyGenerator"
uuid = "40110415-7b45-4700-a6dd-62a19fc43a87"
version = "0.1.0"
authors = ["cgarling <chris.t.garling@gmail.com> and contributors"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
ArgCheck = "2"
Compat = "4"
DataInterpolations = "8"
Distributions = "0.25"
FITSIO = "0.17"
IrrationalConstants = "0.2"
Random = "<0.0.1, 1"
SpecialFunctions = "2"
Trapz = "2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
