name = "GalaxyGenerator"
uuid = "40110415-7b45-4700-a6dd-62a19fc43a87"
authors = ["cgarling <chris.t.garling@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
