[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
GalaxyGenerator = "40110415-7b45-4700-a6dd-62a19fc43a87"
PhotometricFilters = "482c37c2-cde1-4201-a412-83b81535d120"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
GalaxyGenerator = {path = ".."}
